version: '3.4'

services:
  db:
    image: jonasprogrammer/postgres-ip4r:10
    networks:
      - backend-db
    secrets:
      - db-pass
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-pass
      - POSTGRES_DB=some_beautiful_ipam
  nipapd:
    image: jonasprogrammer/nipapd:latest
    ports:
      - "1337:1337"
    networks:
      - backend-db
      - nipap
    secrets:
      - db-pass
      - nipap-pass
    configs:
      - source: nipap-ro-script
        target: /etc/nipap/docker-init.d/add-ro-user.sh
        mode: 0700
    environment:
      - DB_HOST=db
      - DB_NAME=some_beautiful_ipam
      - DB_USERNAME=postgres
      - DB_PASSWORD_FILE=/run/secrets/db-pass
      - NIPAP_USERNAME=toor
      - NIPAP_PASSWORD_FILE=/run/secrets/nipap-pass
      # Use the following for LDAP
#      - AUTH_DEFAULT=false
#      - AUTH_BACKEND=ldap
#      - AUTH_BACKEND_ldap_type=LdapAuth
#      - AUTH_BACKEND_ldap_uri=ldaps://your.company
#      - AUTH_BACKEND_ldap_tls=False
#      - AUTH_BACKEND_ldap_basedn=ou=users,dc=your,dc=company
#      - AUTH_BACKEND_ldap_binddn_fmt=cn={},ou=users,dc=your,dc=company
#      - AUTH_BACKEND_ldap_search=(cn={})
#      - AUTH_BACKEND_ldap_search_binddn=cn=nipap,ou=users,dc=your,dc=company
#      - AUTH_BACKEND_ldap_search_password_FILE=/run/secrets/nipap-pass
#      - AUTH_BACKEND_ldap_rw_group=cn=rw,ou=groups,dc=your,dc=company
#      - AUTH_BACKEND_ldap_ro_group=cn=ro,ou=groups,dc=your,dc=company
  www:
    image: jonasprogrammer/nipapd-www:latest
    ports:
      - "1338:8080"
    networks:
      - nipap
    secrets:
      - nipap-pass
    environment:
      - NIPAPD_HOST=nipapd
      - NIPAPD_USERNAME=toor
      - NIPAPD_PASSWORD_FILE=/run/secrets/nipap-pass
      - WWW_USERNAME=www
      - WWW_PASSWORD=www

networks:
  backend-db:
  nipap:

configs:
  nipap-ro-script:
    file: add-readonly-user.sh

secrets:
  db-pass:
    file: db-pw.txt
  nipap-pass:
    file: nipap-pw.txt
